package:
  name: {{ environ.get('SINGA_NAME', 'singa') }}
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  path: ../../


build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CONDA_BLD_PATH
    - SINGA_INCLUDE_PATH
    - SINGA_LIBRARY_PATH

requirements:
  build:
    - python 2.7* [py27]
    - python 3.6* [py36]
    - numpy >=1.10
    - swig >=3.0
    - openblas >=0.2.10
    - protobuf 3.2
    - glog 0.3.4
    - gcc 4.8.5 # [linux]

  run:
    - python 2.7* [py27]
    - python 3.6* [py36]
    - numpy >=1.10
    - protobuf 3.2
    - glog 0.3.4
    - openblas >=0.2.10
    - flask >=0.10.1
    - flask-cors >=3.0.2
    - pillow >=2.3.0
    - libgcc 4.8.5 # [linux]

test:
  source_files:
    - test/python/*.py
  test:
    - python run.py

about:
  home: http://singa.apache.org/
  license: Apache V2
  license_file: LICENSE
  summary: SINGA is an Apache Incubating project for providing distributed deep learning. Apache disclaimers http://singa.apache.org/en/index.html#disclaimers
